import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import "@/helper/style/globals.css";

import Provider from "@/helper/routing/Provider";

import Pathname from "@/helper/routing/Pathname";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import { ThemeProvider } from "@/utils/theme/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <Pathname>{children}</Pathname>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
